### PR TITLE
Duplex

### PR DESCRIPTION
**Pull request by SwiftSeal**

### CODE REVIEW

**Comment by SwiftSeal** [comment]
Testing just now, but seems functional. @liafrost have a look at the barcode wildcards and you should be able to see how this functions - eventually we could use a pandas dataframe rather than a list called `BARCODES` - this would let us rename each sample, but for now just sticking to barcode01 ... barcode06

**Comment by SwiftSeal** [comment]
Forgot to add SeqIO... Also had to manually `pip install pod5` into the base conda environment. I think there's a way to support pip via conda recipes, but could also just manually change install script

**Comment by liafrost** [comment]
Looks great Moray, its harder for me to follow at home but I understand every action you are taking, I just dont maybe know how you are doing it as I couldnt watch. I appreciate you pushing on this so we can get into the inetrpreation and visual representation next week. I am going to be working all weekend as I have had a few appointments Ive needed to get today as I am never home during business hours lately.

**Review by liafrost — APPROVED** [review]

**Comment by liafrost** [comment]
Let me know if you need anything else, hope you are taking advantage of the free coffee today as its gone forever now. Haha i enjoyed while it lasted.

**Pull request merged**
